import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/utils/provider/AuthProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <AuthProvider>
            <body className={inter.className}>
            <div className="md:px-40">
                {children}
            </div>
            </body>
        </AuthProvider>
        </html>
    );
}
