import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/utils/provider/ReactQueryProvider";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { LocationProvider } from "@/hooks/context/LocationProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quick Basket Grocery",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <ReactQueryProvider>
        <SessionProvider session={session} refetchInterval={120}>
          <LocationProvider>
            <body className={inter.className}>{children}</body>
          </LocationProvider>
        </SessionProvider>
        <ReactQueryDevtools initialIsOpen={true} />
      </ReactQueryProvider>
    </html>
  );
}
